name: Deploy Voil Med

on:
  push:
    branches: ["main"]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Roda Docker Compose
      run: docker compose up -d

    - name: Deploy para EC2
      env:
        PRIVATE_KEY: ${{secrets.EC2_PRIVATE_KEY}}
        USER: ubuntu
        HOST: 18.206.118.172
      run: |
        echo "$PRIVATE_KEY" > new_acesso.pem
        chmod 600 new_acesso.pem

        docker save -o vollmed-api_api.tar vollmed-api_api

        scp -o StrictHostKeyChecking=no -i new_acesso.pem vollmed-api_api.tar $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i new_acesso.pem init.sql $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i new_acesso.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i new_acesso.pem script-deploy.sh $USER@$HOST:/home/ubuntu/  

        ssh -i new_acesso.pem $USER@$HOST "chmod +x script-deploy.sh && ./script-deploy.sh"
